version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-eyang}
      POSTGRES_USER: ${POSTGRES_USER:-prisma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-***}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py seed_admin &&
             daphne -b 0.0.0.0 -p 8000 project.asgi:application"
    ports:
      - "3006:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://localhost:3006,http://127.0.0.1:3006,https://eyangestate.com/,http://147.93.47.169:3006
      - REQUIRE_DB_SSL=False
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    env_file:
      - backend/project/.env
    volumes:
      - media_data:/app/media
      - static_data:/app/static_cdn
    depends_on:
      - db
    restart: unless-stopped


volumes:
  postgres_data:
  media_data:
  static_data:
