# Generated by Django 6.0.2 on 2026-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='global_user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='global_user',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='global_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='global_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
