# Generated by Django 5.1 on 2025-07-28 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estate_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='estate',
            name='forage',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='free',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='room_size',
        ),
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.TextField(default='No description provided yet.'),
        ),
        migrations.AddField(
            model_name='estate',
            name='free_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='estate',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='estate_images/'),
        ),
        migrations.AddField(
            model_name='estate',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estate',
            name='security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='space',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estate',
            name='tv_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estate',
            name='capacity',
            field=models.CharField(help_text="e.g., '124 Rooms'", max_length=100),
        ),
        migrations.AlterField(
            model_name='estate',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estate',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estate',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estatefeature',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app1.estate'),
        ),
        migrations.AddField(
            model_name='estateimage',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.estate'),
        ),
        migrations.AlterUniqueTogether(
            name='estatefeature',
            unique_together={('estate', 'name')},
        ),
    ]
