# Generated by Django 5.1 on 2026-03-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('visitor', 'Visitor/Student'), ('owner', 'Estate Owner')], default='visitor', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='visitor_category',
            field=models.CharField(blank=True, choices=[('1', 'Student'), ('2', 'Parent'), ('3', 'Local resident'), ('4', 'Visitor')], default='1', max_length=20, null=True),
        ),
    ]
