# Generated by Django 5.1 on 2026-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0002_delete_feature_contactrequest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='fridge',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='estate',
            name='tv',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
    ]
