# Generated by Django 5.1 on 2025-07-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_estatefeature_estateimage_delete_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='estateimage',
            name='estate',
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={},
        ),
        migrations.RemoveField(
            model_name='estate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='free_rooms',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='security',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='space',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='tv_fridge',
        ),
        migrations.AddField(
            model_name='estate',
            name='forage',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='estate',
            name='free',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='estates/'),
        ),
        migrations.AddField(
            model_name='estate',
            name='room_size',
            field=models.CharField(choices=[('1', 'Large'), ('2', 'Medium'), ('3', 'Small')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='estate',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estate',
            name='distance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='estate',
            name='generator',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='estate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.IntegerField(default=300000),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rating',
            field=models.CharField(blank=True, default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='estate',
            name='restaurant',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='estate',
            name='wifi',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='EstateFeature',
        ),
        migrations.DeleteModel(
            name='EstateImage',
        ),
    ]
