# Generated by Django 5.1 on 2026-03-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0003_user_id_card_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='free',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='fridge',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='room_size',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='wifi',
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupancy', models.CharField(choices=[('single', 'Single Person'), ('double', 'Two Persons'), ('shared', 'Shared/Multiple Persons')], default='single', max_length=10)),
                ('price', models.IntegerField(default=300000)),
                ('quantity_available', models.IntegerField(default=1)),
                ('wifi', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('tv', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('fridge', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('room_size', models.CharField(choices=[('1', 'Large'), ('2', 'Medium'), ('3', 'Small')], default='2', max_length=1)),
                ('description', models.TextField(blank=True, default='')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='estate_app.estate')),
            ],
        ),
        migrations.AddField(
            model_name='quickorder',
            name='room_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_orders', to='estate_app.roomcategory'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estates/rooms/images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate_app.roomcategory')),
            ],
        ),
    ]
