# Generated by Django 5.1 on 2026-03-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0004_contactrequest_estate_contactrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_user',
            name='status',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Parent'), ('3', 'Owner')], default='1', max_length=20),
        ),
    ]
