# Generated by Django 5.1 on 2026-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0004_remove_estate_capacity_remove_estate_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='location',
            field=models.CharField(default='Eyang', max_length=255),
        ),
    ]
