# Generated by Django 5.1 on 2026-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0005_alter_estate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
