# Generated by Django 5.1 on 2026-04-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0008_estate_lat_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='estate',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=3.884041, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estate',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=11.390736, max_digits=10),
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
