# Generated by Django 5.1 on 2026-04-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0009_remove_quickorder_status_alter_estate_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Approved by an admin. Resets to False when owner edits the estate.'),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='occupancy',
            field=models.CharField(choices=[('single', 'Single Person'), ('double', 'Two Persons'), ('shared', 'Shared')], default='single', max_length=10),
        ),
    ]
