# Generated by Django 5.1 on 2026-05-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0010_estate_is_verified_quickorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='occupied_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_message', 'New Message'), ('new_booking', 'New Booking'), ('new_review', 'New Review'), ('verification_status', 'Verification Status'), ('new_contact', 'New Contact'), ('info', 'Information')], max_length=50)),
                ('title_key', models.CharField(max_length=255)),
                ('body_key', models.CharField(max_length=255)),
                ('body_params', models.JSONField(blank=True, default=dict)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
