# Generated by Django 5.1 on 2026-05-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0011_roomcategory_occupied_count_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, unique=True)),
                ('removable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='estate',
            name='allowed_gender',
            field=models.CharField(choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='estate',
            name='borehole_forage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='caretaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='cleaning_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='electricity_bills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='etages',
            field=models.PositiveIntegerField(default=1, verbose_name='nombre_d_etage'),
        ),
        migrations.AddField(
            model_name='estate',
            name='fence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='generator_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='restaurant_on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='water_bills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='available_quantity',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Estate Owner'), ('parent', 'Parent'), ('student', 'Student'), ('visitor', 'Visitor/Student')], default='visitor', max_length=10),
        ),
        migrations.CreateModel(
            name='EstateCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.characteristic')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='estate_app.estate')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='estate_app.roomcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='estate_app.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_rooms', to='estate_app.roomcategory')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='estate_app.room'),
        ),
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('surface_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('BAD', 'Bad')], default='GOOD', max_length=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.equipment')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='estate_app.roomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='estate_app.estate')),
            ],
        ),
    ]
