# Generated by Django 5.1 on 2026-05-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='is_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Paiement en attente'), ('paid', 'Payée (en attente de validation)'), ('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('payment_failed', 'Paiement échoué')], default='pending_payment', max_length=20),
        ),
    ]
