# Generated by Django 5.1 on 2026-05-07 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0012_characteristic_equipment_estate_allowed_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='custom_characteristics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms of this category reserved.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_details_json',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of estate and room-category at booking time.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='selected_supplements',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='estate_app.supplement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='available_rooms',
            field=models.IntegerField(db_index=True, default=1, help_text='Rooms currently available. Decremented on accept, incremented on cancel/reject.'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Room surface area in m²', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total physical rooms in this category'),
        ),
        migrations.AddField(
            model_name='roomequipment',
            name='note',
            field=models.TextField(blank=True, default='', help_text="Optional note about this equipment item (e.g., 'shared between 2 rooms')"),
        ),
        migrations.AddField(
            model_name='supplement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplement',
            name='is_paid_service',
            field=models.BooleanField(default=False, help_text='True if this supplement has a cost, False if included.'),
        ),
    ]
