# Generated by Django 6.0.2 on 2026-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0013_add_rooms_snapshot_equipment_supplements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=3.884041, max_digits=25),
        ),
        migrations.AlterField(
            model_name='estate',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=11.390736, max_digits=25),
        ),
    ]
