# Generated by Django 6.0.2 on 2026-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0014_alter_estate_lat_alter_estate_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='Terrain_de_sport',
            field=models.BooleanField(default=False),
        ),
    ]
