# Generated by Django 6.0.2 on 2026-05-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0013_quickorder_is_payment_verified_quickorder_receipt_and_more'),
        ('estate_app', '0015_estate_terrain_de_sport'),
    ]

    operations = [
    ]
