# Generated by Django 5.1 on 2026-05-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0016_merge_20260508_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatecharacteristic',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics_set', to='estate_app.estate'),
        ),
        migrations.AlterField(
            model_name='roomequipment',
            name='room_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_set', to='estate_app.roomcategory'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements_set', to='estate_app.estate'),
        ),
    ]
