# Generated by Django 5.1 on 2026-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0017_alter_estatecharacteristic_estate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estate',
            name='tv',
            field=models.BooleanField(default=False),
        ),
    ]
