# Generated by Django 6.0.2 on 2026-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0018_estate_fridge_estate_playground_estate_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
