# Generated by Django 6.0.2 on 2026-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0019_alter_roomcategory_fridge_alter_roomcategory_tv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True, help_text='Note from the client.', null=True),
        ),
    ]
