# Generated by Django 5.1 on 2025-07-22 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=1)),
                ('free', models.IntegerField(default=1)),
                ('rating', models.CharField(blank=True, default='0.0', max_length=10)),
                ('price', models.IntegerField(default=300000)),
                ('distance', models.IntegerField(default=100)),
                ('wifi', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('restaurant', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('generator', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('room_size', models.CharField(choices=[('1', 'Large'), ('2', 'Medium'), ('3', 'Small')], default='2', max_length=1)),
                ('forage', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='estates/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recentposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=1000000)),
                ('author', models.CharField(max_length=50)),
                ('data_aos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Global_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('1', 'Student'), ('2', 'Parent'), ('3', 'Local resident'), ('4', 'Visitor')], default='1', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app1.estate')),
            ],
        ),
    ]
