# Generated by Django 5.1 on 2025-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_estate_distance_remove_estate_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
