# Generated by Django 5.1 on 2025-01-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_estate_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
