# Generated by Django 5.1 on 2025-02-12 22:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_estate_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500),size=10),
        ),
    ]
