# Generated by Django 5.1 on 2025-02-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_estate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='pic',
        ),
    ]
