# Generated by Django 5.1 on 2025-02-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
