# Generated by Django 5.1 on 2025-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
