# Generated by Django 5.1 on 2025-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='image',
        ),
        migrations.AddField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, upload_to='estates/'),
        ),
    ]
