# Generated by Django 5.1 on 2025-06-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_estate_image_estate_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='distance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='estate',
            name='forage',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='generator',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='price',
            field=models.IntegerField(default=300000),
        ),
        migrations.AddField(
            model_name='estate',
            name='restaurant',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='room_size',
            field=models.CharField(choices=[('1', 'Large'), ('2', 'Medium'), ('3', 'Small')], default=1),
        ),
        migrations.AddField(
            model_name='estate',
            name='wifi',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=0),
        ),
    ]
