# Generated by Django 5.1 on 2025-07-09 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_contactrequest_quickorder_alter_estate_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('1', 'Student'), ('2', 'Parent'), ('3', 'Local resident'), ('4', 'Visitor')], default='1', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
